<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\ElysiumDatabase\ElysiumDatabase\Configuration\DatabaseSchemas.cs"
                 Link="Configuration\DatabaseSchemas.cs" />
    </ItemGroup>

</Project>
