<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SkipFunctionsDepsCopy>true</SkipFunctionsDepsCopy>
        <RootNamespace>ElysiumDatabas</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE;SERVER</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\ElysiumDataAccessLayer.Models\ElysiumDataAccessLayer.Models.csproj" />
      <ProjectReference Include="..\..\ElysiumDatabase.EntityFramework\ElysiumDatabase.EntityFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Enums\TableColumns\Table5Columns.cs" />
      <Compile Remove="Enums\TableColumns\Table4Columns.cs" />
      <Compile Remove="Enums\TableColumns\Table3Columns.cs" />
      <Compile Remove="Enums\TableColumns\Table2Columns.cs" />
      <Compile Remove="Enums\TableColumns\Table1Columns.cs" />
    </ItemGroup>

</Project>
