CREATE TABLE [content].[scriptableQuests] (
    [scriptableQuestId]               INT            IDENTITY (1, 1) NOT NULL,
    [questGlobalObject]               VARCHAR (255)  NOT NULL,
    [questlineGlobalObject]           VARCHAR (255)  NOT NULL,
    [questNpcGlobalObject]            VARCHAR (255)  NOT NULL,
    [guaranteedLootTableGlobalObject] VARCHAR (255)  NOT NULL,
    [optionalLootTableGlobalObject]   VARCHAR (255)  NOT NULL,
    [questCategoryTypeId]             TINYINT        NOT NULL,
    [questTypeId]                     TINYINT        NOT NULL,
    [questTierId]                     TINYINT        NOT NULL,
    [questMainTierId]                 TINYINT        NOT NULL,
    [tierAvailableId]                 TINYINT        NOT NULL,
    [questStatusId]                   TINYINT        NOT NULL,
    [questShareable]                  BIT            NOT NULL,
    [guaranteedDrops]                 TINYINT        NOT NULL,
    [optionalDrops]                   TINYINT        NOT NULL,
    [questRewardGold]                 INT            NOT NULL,
    [questRewardSilver]               TINYINT        NOT NULL,
    [questRewardCopper]               TINYINT        NOT NULL,
    [questRewardExperience]           INT            NOT NULL,
    [questDescription]                VARCHAR (1000) NOT NULL,
    [questCompletionDescription]      VARCHAR (1000) NOT NULL,
    [questObjectiveDescription]       VARCHAR (1000) NOT NULL,
    [globalObjectName]                AS             ([dbo].[getGlobalObjectName]([questGlobalObject])),
    [guaranteedLootTableName]         AS             ([dbo].[getGlobalObjectName]([guaranteedLootTableGlobalObject])),
    [optionalLootTableName]           AS             ([dbo].[getGlobalObjectName]([optionalLootTableGlobalObject])),
    [questNpcName]                    AS             ([dbo].[getGlobalObjectName]([questNpcGlobalObject])),
    [questline]                       AS             ([dbo].[getGlobalObjectName]([questlineGlobalObject])),
    [questType]                       AS             ([dbo].[getQuestTypeName]([questTypeId])),
    [tierAvailable]                   AS             ([dbo].[getGlobalTierName]([tierAvailableId])),
    [questCategoryType]               AS             ([dbo].[getQuestCategoryTypeName]([questCategoryTypeId])),
    [questTier]                       AS             ([dbo].[getQuestTier]([questTierId])),
    [questMainTier]                   AS             ([dbo].[getQuestMainTier]([questMainTierId])),
    [questStatus]                     AS             ([dbo].[getQuestStatus]([questStatusId])),
    CONSTRAINT [PK__scriptab__8E221078B52805EB] PRIMARY KEY NONCLUSTERED ([questGlobalObject] ASC),
    CONSTRAINT [FK_scriptableQuests_scriptableObjects] FOREIGN KEY ([questlineGlobalObject]) REFERENCES [content].[scriptableObjects] ([globalObject]),
    CONSTRAINT [FK_scriptableQuests_scriptableObjects1] FOREIGN KEY ([questGlobalObject]) REFERENCES [content].[scriptableObjects] ([globalObject]),
    CONSTRAINT [scriptableQuests_globalTiers_globalTierId_fk] FOREIGN KEY ([tierAvailableId]) REFERENCES [content].[globalTiers] ([typeId]),
    CONSTRAINT [scriptableQuests_globalTiers_globalTierId_fk_2] FOREIGN KEY ([questTierId]) REFERENCES [content].[globalTiers] ([typeId]),
    CONSTRAINT [scriptableQuests_questCategoryTypes_questCategoryTypeId_fk] FOREIGN KEY ([questCategoryTypeId]) REFERENCES [content].[questCategoryTypes] ([typeId]),
    CONSTRAINT [scriptableQuests_questSubTiers_questSubTierId_fk] FOREIGN KEY ([questMainTierId]) REFERENCES [content].[questMainTiers] ([typeId]),
    CONSTRAINT [scriptableQuests_scriptableLootTables_globalObjectCode_fk] FOREIGN KEY ([guaranteedLootTableGlobalObject]) REFERENCES [content].[scriptableLootTables] ([globalObject]),
    CONSTRAINT [scriptableQuests_scriptableLootTables_globalObjectCode_fk_2] FOREIGN KEY ([optionalLootTableGlobalObject]) REFERENCES [content].[scriptableLootTables] ([globalObject]),
    CONSTRAINT [scriptableQuests_scriptableNPCS_globalObjectCode_fk] FOREIGN KEY ([questNpcGlobalObject]) REFERENCES [content].[scriptableNPCS] ([globalObject]),
    CONSTRAINT [UQ__scriptab__8E221078B6A64C6A] UNIQUE NONCLUSTERED ([questGlobalObject] ASC)
);


GO

