CREATE TABLE [ops].[_configDetailsGameObjects] (
    [gameObjectType]                 AS            ([dbo].[getGameObjectType]([gameObjectTypeId])),
    [dataGameObjectType]             AS            ([dbo].[getGameObjectType]([dataGameObjectTypeId])),
    [controlName]                    VARCHAR (100) NOT NULL,
    [panelId]                        VARCHAR (100) NOT NULL,
    [sqlTableNameString]             VARCHAR (100) NOT NULL,
    [globalObjectNamingType]         VARCHAR (100) NOT NULL,
    [globalObjectString]             VARCHAR (100) NOT NULL,
    [globalObjectNameString]         VARCHAR (100) NOT NULL,
    [propertyStringOne]              VARCHAR (100) NOT NULL,
    [propertyStringTwo]              VARCHAR (100) NOT NULL,
    [propertyStringThree]            VARCHAR (100) NOT NULL,
    [webControlAssociated]           VARCHAR (100) NOT NULL,
    [webControlAmount]               VARCHAR (100) NOT NULL,
    [webControlTypeOne]              VARCHAR (100) NOT NULL,
    [webControlTypeTwo]              VARCHAR (100) NOT NULL,
    [webControlTypeThree]            VARCHAR (100) NOT NULL,
    [hasPrefabs]                     BIT           NOT NULL,
    [hasIcons]                       BIT           NOT NULL,
    [description]                    VARCHAR (255) NOT NULL,
    [globalObjectType]               VARCHAR (100) NOT NULL,
    [globalObjectSubType]            VARCHAR (100) NOT NULL,
    [scriptableObjectType]           VARCHAR (100) NOT NULL,
    [typesToIconSearches]            VARCHAR (100) NOT NULL,
    [typesToPrefabSearches]          VARCHAR (100) NOT NULL,
    [typePropertyName]               VARCHAR (100) NOT NULL,
    [typePropertyNameAlt]            VARCHAR (100) NOT NULL,
    [typeTableName]                  VARCHAR (100) NOT NULL,
    [upperType]                      VARCHAR (100) NOT NULL,
    [upperTypePropertyName]          VARCHAR (100) NOT NULL,
    [upperTypeControlName]           VARCHAR (100) NOT NULL,
    [mainType]                       VARCHAR (100) NOT NULL,
    [mainTypePropertyName]           VARCHAR (100) NOT NULL,
    [mainTypeControlName]            VARCHAR (100) NOT NULL,
    [classificationType]             VARCHAR (100) NOT NULL,
    [classificationTypePropertyName] VARCHAR (100) NOT NULL,
    [classificationTypeControlName]  VARCHAR (100) NOT NULL,
    [subType]                        VARCHAR (100) NOT NULL,
    [subTypePropertyName]            VARCHAR (100) NOT NULL,
    [subTypeControlName]             VARCHAR (100) NOT NULL,
    [unitTestMethodName]             VARCHAR (100) NOT NULL,
    [validationMethodName]           VARCHAR (100) NOT NULL,
    [gameObjectTypeId]               TINYINT       NOT NULL,
    [dataGameObjectTypeId]           TINYINT       NOT NULL,
    [sortGroupType]                  VARCHAR (100) NOT NULL,
    [filterOutValues]                VARCHAR (255) NOT NULL,
    [filterOutTypeLevel]             VARCHAR (100) NOT NULL
);


GO

