namespace RebirthStudios.DataAccessLayer.Enums.TableColumns
{
	public enum ScriptableQuestsColumns : byte
	{
		scriptableQuestId = 0,
		questGlobalObject = 1,
		questlineGlobalObject = 2,
		questNpcGlobalObject = 3,
		guaranteedLootTableGlobalObject = 4,
		optionalLootTableGlobalObject = 5,
		questCategoryTypeId = 6,
		questTypeId = 7,
		questTierId = 8,
		questMainTierId = 9,
		tierAvailableId = 10,
		questStatusId = 11,
		questShareable = 12,
		guaranteedDrops = 13,
		optionalDrops = 14,
		questRewardGold = 15,
		questRewardSilver = 16,
		questRewardCopper = 17,
		questRewardExperience = 18,
		questDescription = 19,
		questCompletionDescription = 20,
		questObjectiveDescription = 21,
		globalObjectName = 22,
		guaranteedLootTableName = 23,
		optionalLootTableName = 24,
		questNpcName = 25,
		questline = 26,
		questType = 27,
		tierAvailable = 28,
		questCategoryType = 29,
		questTier = 30,
		questMainTier = 31,
		questStatus = 32,
	}
}
